# Generated by Django 3.0.2 on 2020-05-04 18:50

from django.db import migrations, models
import recognize_img.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognize_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=recognize_img.models.user_directory_path)),
            ],
        ),
    ]
