# Generated by Django 3.0.2 on 2020-05-07 09:53

from django.db import migrations, models
import recognize_img.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize_img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicted_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_predicted', models.FileField(upload_to=recognize_img.models.user_directory_path1)),
                ('p_name', models.CharField(max_length=20)),
            ],
        ),
    ]
