# Generated by Django 3.0.2 on 2020-05-03 10:12

from django.db import migrations, models
import django.db.models.deletion
import upload_img.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=upload_img.models.user_directory_path)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upload_img.Person')),
            ],
        ),
    ]
